# Generated by Django 4.2.1 on 2023-06-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamePassed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название игры')),
                ('hours_played', models.PositiveIntegerField(blank=True, null=True, verbose_name='Часы, потраченные на прохождение')),
                ('developer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Разработчик')),
            ],
            options={
                'verbose_name': 'Пройденные игры',
                'verbose_name_plural': 'Пройденные игры',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('games', models.ManyToManyField(blank=True, default=None, related_name='users', to='loginer.gamepassed', verbose_name='Игры, которые прошел')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
