# Generated by Django 4.2.1 on 2023-06-04 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Возрастная категория',
                'verbose_name_plural': 'Возрастная категория',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=255, verbose_name='Имя разработчика')),
            ],
            options={
                'verbose_name': 'Разработчики',
                'verbose_name_plural': 'Разработчики',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=255, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанры',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('rate', models.SmallIntegerField(verbose_name='Оценка')),
                ('full_review', models.TextField(verbose_name='Полный текст отзыва')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255, verbose_name='Название игры')),
                ('description', models.TextField(default='Игра', verbose_name='Описание игры')),
                ('img', models.ImageField(upload_to='game_img', verbose_name='Фото игры')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.agecategory')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.developer')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.genre')),
                ('reviews', models.ManyToManyField(blank=True, related_name='games', to='review.review', verbose_name='Отзывы')),
            ],
            options={
                'verbose_name': 'Игры',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
